#import <AppKit/AppKit.h>
#include <stdlib.h>
#include <string.h>

// Пометки для менеджеров буфера обмена (nspasteboard.org): данные временные, в историю не сохранять.
static NSString *const transientType = @"org.nspasteboard.TransientType";
static NSString *const autoGeneratedType = @"org.nspasteboard.AutoGeneratedType";

// NSPasteboard используется только из главного потока.

char *lsClipText(void) {
	__block char *res = NULL;
	dispatch_sync(dispatch_get_main_queue(), ^{
		@autoreleasepool {
			NSString *s = [[NSPasteboard generalPasteboard] stringForType:NSPasteboardTypeString];
			if (s != nil) {
				res = strdup(s.UTF8String);
			}
		}
	});
	return res;
}

void lsClipSetText(const char *s) {
	dispatch_sync(dispatch_get_main_queue(), ^{
		@autoreleasepool {
			NSString *str = [NSString stringWithUTF8String:s];
			if (str == nil) {
				str = @"";
			}
			NSPasteboard *pb = [NSPasteboard generalPasteboard];
			[pb declareTypes:@[NSPasteboardTypeString, transientType, autoGeneratedType] owner:nil];
			[pb setString:str forType:NSPasteboardTypeString];
			[pb setData:[NSData data] forType:transientType];
			[pb setData:[NSData data] forType:autoGeneratedType];
		}
	});
}

// lsClipSave возвращает массив элементов буфера {тип: данные}; освобождается в lsClipRestore.
void *lsClipSave(void) {
	__block NSArray *saved = nil;
	dispatch_sync(dispatch_get_main_queue(), ^{
		@autoreleasepool {
			NSMutableArray *items = [NSMutableArray array];
			for (NSPasteboardItem *item in [[NSPasteboard generalPasteboard] pasteboardItems]) {
				NSMutableDictionary *d = [NSMutableDictionary dictionary];
				for (NSPasteboardType t in item.types) {
					NSData *data = [item dataForType:t];
					if (data != nil) {
						d[t] = data;
					}
				}
				[items addObject:d];
			}
			saved = [items copy];
		}
	});
	return saved;
}

void lsClipRestore(void *p) {
	NSArray *saved = p;
	dispatch_sync(dispatch_get_main_queue(), ^{
		@autoreleasepool {
			NSPasteboard *pb = [NSPasteboard generalPasteboard];
			[pb clearContents];
			NSMutableArray *items = [NSMutableArray array];
			for (NSDictionary *d in saved) {
				NSPasteboardItem *item = [[[NSPasteboardItem alloc] init] autorelease];
				for (NSPasteboardType t in d) {
					[item setData:d[t] forType:t];
				}
				[items addObject:item];
			}
			if (items.count > 0) {
				// Содержимое уже есть в истории — не дублируем.
				[items[0] setData:[NSData data] forType:transientType];
				[pb writeObjects:items];
			}
		}
	});
	[saved release];
}
